# Generated by Django 4.2.11 on 2025-04-16 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import src.electric_app.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('supplier_name', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('specific_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('info', models.JSONField(default=[])),
                ('status', enumfields.fields.EnumField(default='Unpaid', enum=src.electric_app.enums.InvoiceStatus, max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(default='', upload_to='invoices/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_follow_up_sent', models.BooleanField(default=False)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('info', models.JSONField(default=[])),
                ('status', enumfields.fields.EnumField(default='Unpaid', enum=src.electric_app.enums.InvoiceStatus, max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(default='', upload_to='invoices/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_follow_up_sent', models.BooleanField(default=False)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('quotation_number', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('hours_worked', models.PositiveIntegerField(default=0)),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('overtime_pay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100)),
                ('status', enumfields.fields.EnumField(default='Not Sent', enum=src.electric_app.enums.PayslipStatus, max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='payslip/')),
                ('deduction', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100)),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
