# Generated by Django 4.2.11 on 2025-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
