# Generated by Django 4.2.11 on 2025-05-05 22:18

from django.conf import settings
from django.db import migrations, models
import enumfields.fields
import src.electric_app.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_app', '0002_alter_supplier_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('before_work_picture', models.ImageField(blank=True, null=True, upload_to='tasks')),
                ('after_work_picture', models.ImageField(blank=True, null=True, upload_to='tasks')),
                ('work_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', enumfields.fields.EnumField(default='Created', enum=src.electric_app.enums.TaskStatus, max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('assignees', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
